# docker-compose.yml
version: "3.8"
services:
  client:
    build: ./frontend
    container_name: book-client
    ports:
      - "5173:80"
    environment:
      VITE_BACKEND_DOMAIN: http://127.0.0.1:3000
      MONGODB_URI: mongodb+srv://minhnguyen:superpassword@cluster0.lfo7s.mongodb.net/api-book?retryWrites=true&w=majority
      MONGODB_DB: api-book

  backend:
    container_name: book-backend
    build: ./backend
    environment:
      SERVER_HOST: 127.0.0.1
      SERVER_PORT: 3000
      SERVER_HOST_NAME: 127.0.0.1:3000
      CLIENT_DOMAIN: http://127.0.0.1:5173
      BASE_URL: /api/book
      DOCS_BASE_URL: /docs/book
      DISCORD_APP_ID: 1077791781065867334
      DISCORD_APP_SECRET: qdTIcTv0qQ5m2ZMfv4SFJmpsUgBzlOPS
      DISCORD_REDIRECT_URI: http://127.0.0.1:3000/api/book/auth/callback
      SESSION_SECRET: book
      DB_URI: mongodb+srv://minhnguyen:superpassword@cluster0.lfo7s.mongodb.net/api-book?retryWrites=true&w=majority

    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
